-- Mesma base, na versao do banco de arquivo (H2), usada para rodar na maquina
-- sem instalar servidor. O banco de verdade e o de postgresql/.
-- Quando trocar, o esquema e o mesmo; muda so o tipo de algumas colunas.

create table empresa (
    id           uuid primary key,
    apelido      varchar(60)  not null unique,
    nome         varchar(200) not null,
    cnpj         varchar(20),
    chave_pix    varchar(200),
    erp_setor_id uuid,
    ativa        boolean      not null default true,
    criada_em    timestamp with time zone not null default now()
);

create table usuario (
    id             uuid primary key,
    nome           varchar(200) not null,
    email          varchar(200) not null unique,
    erp_usuario_id uuid unique,
    ativo          boolean      not null default true,
    criado_em      timestamp with time zone not null default now()
);

create table usuario_empresa (
    usuario_id uuid        not null references usuario (id),
    empresa_id uuid        not null references empresa (id),
    papel      varchar(20) not null default 'OPERADOR',
    primary key (usuario_id, empresa_id)
);

create table cliente_espelho (
    id              uuid primary key,
    empresa_id      uuid         not null references empresa (id),
    erp_cliente_id  uuid,
    razao_social    varchar(300) not null,
    cnpj_cpf        varchar(20),
    responsavel     varchar(200),
    telefone        varchar(40),
    email           varchar(200),
    ativo           boolean      not null default true,
    sincronizado_em timestamp with time zone not null default now(),
    constraint uq_cliente_por_empresa unique (empresa_id, erp_cliente_id)
);

create index idx_cliente_empresa on cliente_espelho (empresa_id);

create table titulo (
    id                  uuid primary key,
    empresa_id          uuid           not null references empresa (id),
    cliente_id          uuid           not null references cliente_espelho (id),
    numero              bigint         not null,
    competencia         date           not null,
    descricao           varchar(300)   not null,
    valor               numeric(14, 2) not null check (valor > 0),
    vencimento          date           not null,
    situacao            varchar(20)    not null default 'ABERTO',
    origem              varchar(30)    not null default 'MANUAL',
    identificador_pix   varchar(60),
    observacao          varchar(1000),
    criado_em           timestamp with time zone not null default now(),
    criado_por          varchar(120),
    atualizado_em       timestamp with time zone not null default now(),
    cancelado_em        timestamp with time zone,
    cancelado_por       varchar(120),
    motivo_cancelamento varchar(500),
    constraint uq_titulo_numero unique (empresa_id, numero),
    constraint uq_titulo_pix unique (empresa_id, identificador_pix)
);

create index idx_titulo_cliente on titulo (cliente_id);
create index idx_titulo_vencimento on titulo (empresa_id, vencimento);

create table pagamento (
    id            uuid primary key,
    empresa_id    uuid           not null references empresa (id),
    titulo_id     uuid           not null references titulo (id),
    valor         numeric(14, 2) not null check (valor > 0),
    pago_em       date           not null,
    forma         varchar(30)    not null default 'PIX',
    transacao_id  varchar(120),
    conferido_por varchar(120),
    observacao    varchar(1000),
    criado_em     timestamp with time zone not null default now()
);

create index idx_pagamento_titulo on pagamento (titulo_id);

-- O banco de arquivo nao aceita indice com condicao. A trava de pagamento
-- repetido, aqui, e feita pelo proprio sistema antes de gravar.

create table evento (
    id          bigint generated by default as identity primary key,
    empresa_id  uuid         not null references empresa (id),
    entidade    varchar(60)  not null,
    entidade_id uuid         not null,
    acao        varchar(60)  not null,
    autor       varchar(120),
    detalhe     varchar(4000),
    ocorrido_em timestamp with time zone not null default now()
);

create index idx_evento_entidade on evento (empresa_id, entidade, entidade_id);

create table fila_espelho_erp (
    id            bigint generated by default as identity primary key,
    empresa_id    uuid          not null references empresa (id),
    tipo          varchar(60)   not null,
    referencia_id uuid          not null,
    carga         varchar(4000) not null,
    tentativas    int           not null default 0,
    enviado_em    timestamp with time zone,
    erro          varchar(1000),
    criado_em     timestamp with time zone not null default now()
);
