-- Modulo de integracoes, na versao do banco de arquivo.

create table integracao (
    id                   uuid primary key,
    empresa_id           uuid          not null references empresa (id),
    provedor             varchar(40)   not null,
    nome                 varchar(200)  not null,
    ambiente             varchar(20)   not null default 'PRODUCAO',
    base_url             varchar(500),
    credenciais_cifradas varchar(8000),
    webhook_segredo      varchar(80)   not null,
    ativa                boolean       not null default false,
    ultima_checagem_em   timestamp with time zone,
    ultima_checagem_ok   boolean,
    ultima_checagem_erro varchar(1000),
    observacao           varchar(1000),
    criada_em            timestamp with time zone not null default now(),
    criada_por           varchar(120),
    atualizada_em        timestamp with time zone not null default now(),
    constraint uq_integracao_nome unique (empresa_id, nome)
);

create index idx_integracao_empresa on integracao (empresa_id);

create table integracao_evento (
    id            bigint generated by default as identity primary key,
    integracao_id uuid          not null references integracao (id),
    empresa_id    uuid          not null references empresa (id),
    direcao       varchar(10)   not null,
    tipo          varchar(80)   not null,
    referencia    varchar(200),
    carga         varchar(8000),
    status        varchar(20)   not null default 'RECEBIDO',
    erro          varchar(1000),
    ocorrido_em   timestamp with time zone not null default now(),
    processado_em timestamp with time zone
);

create index idx_evento_integracao on integracao_evento (integracao_id, ocorrido_em);
